<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//debug mail
$config['development_mail'] = 'honma@zeus.corp.813.co.jp';
$config['testing_mail']     = 'keiichi-honma@813.co.jp';

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']    = '';
$config['lang_base_url']    = '';

/*
|--------------------------------------------------------------------------
| show message settings
|
| 'show_message_url' = show message url.
|--------------------------------------------------------------------------
*/
$config['show_message_url'] = 'user/message';
$config['show_message_cart_url'] = 'cart/message';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'            Default - auto detects
| 'PATH_INFO'        Uses the PATH_INFO
| 'QUERY_STRING'    Uses the QUERY_STRING
| 'REQUEST_URI'        Uses the REQUEST_URI
| 'ORIG_PATH_INFO'    Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']    = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
// 国際化
$config['language'] = 'japanese';
$config['language_min'] = 'ja';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
//maintenance
$config['enable_hooks'] = FALSE; // フック機能を有効にする
$config['maintenance'] = FALSE; // メンテナンスモードを有効にする場合はTRUE
$config['maintenance_view'] = 'maintenance'; // メンテナンスモードで表示させるViewファイル

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']        = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']    = 'c';
$config['function_trigger']        = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|    0 = Disables logging, Error logging TURNED OFF
|    1 = Error Messages (including PHP errors)
|    2 = Debug Messages
|    3 = Informational Messages
|    4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'oia8e3e0ae0aowao90823a';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'        = the name you want for the cookie
| 'sess_expiration'            = the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'    = Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'        = Whether to encrypt the cookie
| 'sess_use_database'        = Whether to save the session data to a database
| 'sess_table_name'            = The name of the session database table
| 'sess_match_ip'            = Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'    = Whether to match the User Agent when reading the session data
| 'sess_time_to_update'        = how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']        = 'ci_session';
$config['sess_expiration']        = 86400;//default 7200
$config['sess_expire_on_close']    = TRUE;
$config['sess_encrypt_cookie']    = TRUE;
$config['sess_use_database']    = FALSE;
$config['sess_table_name']        = 'ci_sessions';
$config['sess_match_ip']        = FALSE;
$config['sess_match_useragent']    = TRUE;
$config['sess_time_to_update']    = 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']    = "";
$config['cookie_domain']    = "";
$config['cookie_path']        = "/";
$config['cookie_secure']    = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token_mirai_tenki';
$config['csrf_cookie_name'] = 'csrf_cookie_mirai_tenki';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';
$is_console = FALSE;
//if(in_array('console',explode('/',$_SERVER['PHP_SELF']))) $is_console = TRUE;
//var_dump($_SERVER['PHP_SELF']);//タイ環境だと動かない
if(isset($_SERVER['REQUEST_URI']) && in_array('console',explode('/',$_SERVER['REQUEST_URI']))) $is_console = TRUE;
/*
|--------------------------------------------------------------------------
| Dynamic CSS Setting
|--------------------------------------------------------------------------
|
*/
/*
|--------------------------------------------------------------------------
| Dynamic JS Setting
|--------------------------------------------------------------------------
|
*/
$config['stylesheets'][] = 'css/master.css';
$config['stylesheets'][] = 'css/jquery.sidr.dark.css';
$config['stylesheets'][] = 'css/jquery-ui-1.10.3.custom.css';
$config['stylesheets'][] = 'css/main.css';
$config['stylesheets'][] = ENVIRONMENT == 'localhost' ? 'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css' : 'css/font-awesome.min.css';
$config['stylesheets'][] = 'css/jquery.notifyBar.css';

$config['javascripts'][] = 'js/jquery-1.8.3.js';//slideでも使用
$config['javascripts'][] = 'js/jquery.sidr.min.js';//scroll
$config['javascripts'][] = 'http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js';//scroll
$config['javascripts'][] = 'js/scrolltop.js';//scroll
$config['javascripts'][] = 'js/jquery.notifyBar.js';

/*
|--------------------------------------------------------------------------
| Upload folder setting
|--------------------------------------------------------------------------
|
*/
$config['upload_folder_top'] = 'uploads';
$config['upload_temporary_folder'] = 'tmp';
$config['upload_comics_folder'] = 'comics';
$config['upload_profile_folder'] = 'profiles';

/*
|--------------------------------------------------------------------------
| Upload folder setting
|--------------------------------------------------------------------------
|
| EMERG   = 0;  // Emergency: system is unusable
| ALERT   = 1;  // Alert: action must be taken immediately
| CRIT    = 2;  // Critical: critical conditions
| ERR     = 3;  // Error: error conditions
| WARN    = 4;  // Warning: warning conditions
| NOTICE  = 5;  // Notice: normal but significant condition
| INFO    = 6;  // Informational: informational messages
| DEBUG   = 7;  // Debug: debug messages
|
*/
//$config['zend_log_filters'][] = 0;
//$config['zend_log_filters'][] = 1;
//$config['zend_log_filters'][] = 2;
//$config['zend_log_filters'][] = 3;
//$config['zend_log_filters'][] = 4;
//$config['zend_log_filters'][] = 5;
//$config['zend_log_filters'][] = 6;
//$config['zend_log_filters'][] = 7;
$config['zend_start_log_level'] = 7;
$config['zend_end_log_level'] = 0;
$config['zend_log_filename'] = APPPATH . 'logs/log-' . date( 'Y-m-d' ) . EXT;

/*
|--------------------------------------------------------------------------
| setting
|--------------------------------------------------------------------------
|
*/

$config['jma_weather_start_year'] = 1967;//1967から天気がある
//$config['jma_weather_start_year'] = 1993;//1993からを有効年とする

/*
|--------------------------------------------------------------------------
| paging setting
|--------------------------------------------------------------------------
|
*/

$config['page_link_number'] = 5;
$config['paging_row_count'] = 1;
$config['paging_column_count'] = 50;
$config['paging_count_per_page'] = $config['paging_row_count'] * $config['paging_column_count'];

$config['cdata_page_link_number'] = 5;
$config['cdata_paging_row_count'] = 1;
$config['cdata_paging_column_count'] = 50;
$config['cdata_paging_count_per_page'] = $config['cdata_paging_row_count'] * $config['cdata_paging_column_count'];

$config['paging_count_per_index_page'] = 1 * 20;
$config['paging_count_per_manage_page'] = 10;
/*
|--------------------------------------------------------------------------
| max min setting
|--------------------------------------------------------------------------
|
*/
$config['sp_display_number'] = 1;

$config['name_min_length'] = 1;
$config['name_max_length'] = 100;
$config['contact_comments_max_length'] = 1000;
$config['cart_max_select_number'] = 30;

/*
|--------------------------------------------------------------------------
| allowed upload file type
|--------------------------------------------------------------------------
|
*/
$config['allowed_upload_file_type'] = 'gif|jpg|jpeg|png';

/*
|--------------------------------------------------------------------------
| tools setting
|--------------------------------------------------------------------------
|
*/

//$config['tools_magazine_span_time'] = 600;//1時間に1度チェックし、後ろ10分以内にあるメルマガを有効
$config['tools_magazine_span_time'] = 2400;//1時間に1度チェックし、後ろ40分以内にあるメルマガを有効

$config['company_name_index'] = array('FilerNameInJapaneseDEI','EntityInformationDEIAbstract');
$config['edinet_code_index'] = array('EDINETCodeDEI');
$config['date_index'] = array('FilingDateCoverPage');
$config['document_title_index'] = array('DocumentTitleCoverPage');
$config['document_title_special_index'] = array('GenericNameOfEntityJaEntityInformation','EntityNameJaEntityInformation');
$config['document_info_index'] = array('DocumentTitleCoverPage','GenericNameOfEntityJaEntityInformation','EntityNameJaEntityInformation');


/*
|--------------------------------------------------------------------------
| string max length 
|--------------------------------------------------------------------------
|
*/

$config['string_max_length'] = 1000;

/*
|--------------------------------------------------------------------------
| allowed download file type
|--------------------------------------------------------------------------
|
*/
$config['allowed_download_file_type'] = array('csv','xlsx');

/* End of file config.php */
/* Location: ./application/config/config.php */
